# Generated by Django 4.1.3 on 2022-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type1', models.CharField(max_length=200)),
                ('type2', models.CharField(max_length=200, null='true')),
                ('image', models.CharField(max_length=500)),
                ('rarity', models.CharField(max_length=500)),
                ('generation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemonID', models.IntegerField()),
                ('UserID', models.IntegerField()),
                ('dateRolled', models.DateField()),
            ],
        ),
    ]
