# Generated by Django 4.1.3 on 2022-12-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(blank='true', max_length=200, null='true'),
        ),
    ]
